name: Conditional Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt


    - name: Run Python tests
      if: contains(github.event.pull_request.changed_files, '.py')
      run: FE-test.yml


    - name: Lint Python code
      if: contains(github.event.pull_request.changed_files, '.py')
      run: pylint src/

      
    - name: Install Node.js
      if: contains(github.event.pull_request.changed_files, '.js')
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16.x'

    - name: Install Node.js dependencies
      if: contains(github.event.pull_request.changed_files, '.js')
      run: npm install
    - name: Run React tests
      if: contains(github.event.pull_request.changed_files, '.js')
      run: FE-test.yml
    - name: Run ML tests
      if: contains(github.event.pull_request.changed_files, '.py')
      run: ML-test.yml

    - name: Request review
      uses: reviewdog/action-github-pr-review@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        tool_name: pylint
        filter_mode: file
        level: warning
        reviewdog_flags: -diff="git diff HEAD^ HEAD --name-only" -reporter=github-pr-review -level=warning -fail-on-error

  merge:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() }}
    steps:
    - name: Merge pull request
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Automated merge
        title: Automated merge
        branch: main
        body: Automated merge 
        delete-branch: true 
