name: PR Gate

on:
  pull_request:
    branches: [ main ]
  
jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Call ML test
        if: ${{ endsWith(github.event.pull_request.head.ref, '.py') }}
        uses: ./ML-test.yml

  node-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        if: ${{ endsWith(github.event.pull_request.head.ref, '.js') }}
        run: npm install
      - name: Run tests
        if: ${{ endsWith(github.event.pull_request.head.ref, '.js') }}
        run: npm test
      - name: Call FE test
        if: ${{ endsWith(github.event.pull_request.head.ref, '.js') }}
        uses: ./FE-test.yml
