name: Pull Request Workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    name: Approval Check of PR
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"





